group_vars/all: downgrade SIP version to avoid compiler errors
The errors are are follows with the previous SIP
version:

    /usr/local/lib/Qt/5.13.1/gcc_64/include/QtQml/qjsengine.h:103:24: note: declared here
         QT_DEPRECATED void installTranslatorFunctions(const QJSValue &object = QJSValue());
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~
    /tmp/pyQt/PyQt5_gpl-5.13.1/QtQuick/sipQtQuickQQuickWindow.cpp: In function PyObject* meth_QQuickWindow_sendEvent(PyObject*, PyObject*):
    /tmp/pyQt/PyQt5_gpl-5.13.1/QtQuick/sipQtQuickQQuickWindow.cpp:824:45: warning: bool QQuickWindow::sendEvent(QQuickItem*, QEvent*) is deprecated [-Wdeprecated-declarations]
                 sipRes = sipCpp->sendEvent(a0,a1);
                                                 ^
    In file included from /tmp/pyQt/PyQt5_gpl-5.13.1/sip/QtQuick/qquickwindow.sip:26:0,
                     from sipQtQuickQQuickWindow.cpp:24:
    /usr/local/lib/Qt/5.13.1/gcc_64/include/QtQuick/qquickwindow.h:124:24: note: declared here
         QT_DEPRECATED bool sendEvent(QQuickItem *, QEvent *);
                            ^~~~~~~~~
    /tmp/pyQt/PyQt5_gpl-5.13.1/QtQuick/sipQtQuickQSGGeometry.cpp: In function void assign_QSGGeometry(void*, Py_ssize_t, void*):
    /tmp/pyQt/PyQt5_gpl-5.13.1/QtQuick/sipQtQuickQSGGeometry.cpp:940:103: error: use of deleted function QSGGeometry& QSGGeometry::operator=(const QSGGeometry&)
         {
                                                                                                           ^
    In file included from /usr/local/lib/Qt/5.13.1/gcc_64/include/QtQuick/qsgnode.h:43:0,
                     from /usr/local/lib/Qt/5.13.1/gcc_64/include/QtQuick/qsgrendererinterface.h:43,
                     from /usr/local/lib/Qt/5.13.1/gcc_64/include/QtQuick/qquickwindow.h:44,
                     from /tmp/pyQt/PyQt5_gpl-5.13.1/sip/QtQuick/qquickwindow.sip:26,
                     from sipQtQuickQSGGeometry.cpp:24:
    /usr/local/lib/Qt/5.13.1/gcc_64/include/QtQuick/qsggeometry.h:51:22: note: QSGGeometry& QSGGeometry::operator=(const QSGGeometry&) is implicitly deleted because the default definition would be ill-formed:
     class Q_QUICK_EXPORT QSGGeometry
                          ^~~~~~~~~~~
    /usr/local/lib/Qt/5.13.1/gcc_64/include/QtQuick/qsggeometry.h:51:22: error: non-static reference member const QSGGeometry::AttributeSet& QSGGeometry::m_attributes, cant use default assignment operator
    make[1]: *** [sipQtQuickQSGGeometry.o] Error 1
    make[1]: *** Waiting for unfinished jobs....
    make: *** [sub-QtQuick-make_first-ordered] Error 2

My guess is that hosts were using this old SIP version for a long
and since we didn't change PyQT5 version, SIP was not updated as well.